# Generated by Django 5.1.6 on 2025-02-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('visitor_type', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('approval', models.IntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'Pending')], default=2)),
            ],
        ),
    ]
