# Generated by Django 5.1.6 on 2025-02-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
        ('collegeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='college_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.college'),
        ),
    ]
